const API_SERVER_HOST = import.meta.env.VITE_API_SERVER_HOST;
const API_MOCK_SERVER_HOST = import.meta.env.VITE_API_MOCK_SERVER_HOST;
const API_SERVER_DOMAIN = import.meta.env.VITE_API_SERVER_DOMAIN
const API_FCM_HOST = import.meta.env.VITE_API_FCM_DOMAIN

const SIGNALING_SERVER_URL = import.meta.env.VITE_SOCKET_SERVER_URL

export {API_SERVER_HOST, API_MOCK_SERVER_HOST, API_SERVER_DOMAIN, SIGNALING_SERVER_URL,API_FCM_HOST}