const API_SERVER_HOST = import.meta.env.VITE_API_SERVER_HOST;
const API_MOCK_SERVER_HOST = import.meta.env.VITE_API_MOCK_SERVER_HOST;
const API_SERVER_DOMAIN = import.meta.env.VITE_API_SERVER_DOMAIN

export {API_SERVER_HOST, API_MOCK_SERVER_HOST, API_SERVER_DOMAIN}